%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

%global __cmake_in_source_build 1

Name:           ros-humble-play-motion2-msgs
Version:        1.8.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS play_motion2_msgs package

License:        Apache License 2.0
URL:            https://github.com/pal-robotics/play_motion2
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-action-msgs
Requires:       ros-humble-builtin-interfaces
Requires:       ros-humble-rosidl-default-runtime
Requires:       ros-humble-ros-workspace
BuildRequires:  ros-humble-action-msgs
BuildRequires:  ros-humble-ament-cmake
BuildRequires:  ros-humble-builtin-interfaces
BuildRequires:  ros-humble-rosidl-default-generators
BuildRequires:  ros-humble-ros-workspace
BuildRequires:  ros-humble-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-humble-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-humble-rosidl-interface-packages(member)

%if 0%{?with_tests}
BuildRequires:  ros-humble-ament-lint-common
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-humble-rosidl-interface-packages(all)
%endif

%description
Play a pre-recorded motion on a robot

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Wed Feb 11 2026 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.8.3-1
- Autogenerated by Bloom

* Thu Nov 20 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.8.2-1
- Autogenerated by Bloom

* Fri Oct 31 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.8.1-1
- Autogenerated by Bloom

* Wed Oct 22 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.8.0-1
- Autogenerated by Bloom

* Thu Sep 18 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.7.0-1
- Autogenerated by Bloom

* Wed Jun 18 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.5.3-1
- Autogenerated by Bloom

* Tue May 13 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.5.2-1
- Autogenerated by Bloom

* Tue Mar 11 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.5.1-1
- Autogenerated by Bloom

* Fri Mar 07 2025 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.5.0-1
- Autogenerated by Bloom

* Thu Sep 12 2024 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.3.0-1
- Autogenerated by Bloom

* Fri Jul 05 2024 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.1.2-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.1.1-1
- Autogenerated by Bloom

* Wed Apr 03 2024 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.1.0-1
- Autogenerated by Bloom

* Fri Mar 01 2024 Noel Jimenez <noel.jimenez@pal-robotics.com> - 1.0.0-1
- Autogenerated by Bloom

* Mon Dec 18 2023 Noel Jimenez <noel.jimenez@pal-robotics.com> - 0.0.13-1
- Autogenerated by Bloom

* Mon Oct 02 2023 Noel Jimenez <noel.jimenez@pal-robotics.com> - 0.0.10-1
- Autogenerated by Bloom

* Wed Jul 05 2023 Noel Jimenez <noel.jimenez@pal-robotics.com> - 0.0.9-1
- Autogenerated by Bloom

* Tue May 23 2023 Noel Jimenez <noel.jimenez@pal-robotics.com> - 0.0.8-1
- Autogenerated by Bloom

* Mon Apr 17 2023 Noel Jimenez <noel.jimenez@pal-robotics.com> - 0.0.7-1
- Autogenerated by Bloom

* Fri Feb 24 2023 Noel Jimenez <noel.jimenez@pal-robotics.com> - 0.0.4-1
- Autogenerated by Bloom

